import fs from 'node:fs';
import assert from 'node:assert/strict';
const root=new URL('..',import.meta.url).pathname;
const server=fs.readFileSync(root+'server.js','utf8');
const html=fs.readFileSync(root+'index.html','utf8');
assert.match(server,/app\.post\('\/api\/games\/:id\/rating',requireAuth/);
assert.match(server,/app\.post\('\/api\/packs\/:id\/rating',requireAuth/);
assert.match(server,/app\.post\('\/api\/games\/:id\/reviews',requireAuth/);
assert.match(server,/app\.post\('\/api\/packs\/:id\/reviews',requireAuth/);
assert.doesNotMatch(server,/PURCHASE_REQUIRED/);
assert.match(html,/برای ثبت رأی و نظر باید وارد حساب کاربری شوید/);
assert.match(html,/async function rateGame\(id,n\)\{if\(!token\)/);
assert.match(html,/async function ratePack\(id,n\)\{if\(!token\)/);
assert.match(html,/function previewAvatar\(input\)/);
assert.match(html,/در حال بارگذاری تصویر پروفایل/);
assert.match(html,/avatarUploadStatus/);
assert.match(html,/async function saveContent\(e,type,oldId\)/);
assert.match(html,/در حال ذخیره اطلاعات در پایگاه داده/);
assert.match(html,/\/admin\/images\/upload/);
console.log('Phase 15 login, review, vote, upload and save checks passed');
