import fs from 'node:fs';
import assert from 'node:assert/strict';
const root=new URL('..',import.meta.url).pathname;
const server=fs.readFileSync(root+'server.js','utf8');
const db=fs.readFileSync(root+'db.js','utf8');
const html=fs.readFileSync(root+'index.html','utf8');
assert.match(db,/CREATE TABLE IF NOT EXISTS pack_ratings/);
assert.match(db,/CREATE TABLE IF NOT EXISTS pack_reviews/);
assert.match(server,/function ownsGame\(userId,gameId\)/);
assert.doesNotMatch(server,/PURCHASE_REQUIRED/);
assert.match(server,/app\.post\('\/api\/games\/:id\/rating',requireAuth/);
assert.match(server,/app\.post\('\/api\/packs\/:id\/rating',requireAuth/);
assert.match(server,/app\.post\('\/api\/games\/:id\/reviews',requireAuth/);
assert.match(server,/app\.post\('\/api\/packs\/:id\/reviews',requireAuth/);
assert.match(server,/app\.post\('\/api\/packs\/:id\/rating'/);
assert.match(server,/app\.post\('\/api\/packs\/:id\/reviews'/);
assert.match(server,/app\.patch\('\/api\/reviews\/:id'/);
assert.match(server,/app\.delete\('\/api\/reviews\/:id'/);
assert.match(server,/ALREADY_REPORTED/);
assert.match(server,/support_notifications/);
assert.match(html,/async function loadNotifications\(\)/);
assert.match(html,/markAllNotifications/);
assert.match(server,/app\.post\('\/api\/pack-reviews\/:id\/report'/);
assert.match(server,/app\.get\('\/api\/notifications'/);
assert.match(server,/notifications.*read_at/);
assert.match(html,/async function loadAdminReviews\(\)/);
assert.match(html,/rateGame/);
assert.match(html,/submitGameReview/);
assert.match(html,/reviewHtml/);
console.log('Phase 11 static tests: 23/23 passed');
