import fs from 'node:fs';
import assert from 'node:assert/strict';
const root=new URL('..',import.meta.url).pathname;
const server=fs.readFileSync(root+'server.js','utf8');
const db=fs.readFileSync(root+'db.js','utf8');
const html=fs.readFileSync(root+'index.html','utf8');
const unified=fs.readFileSync(root+'gt-unified.js','utf8');
const phase=fs.readFileSync(root+'PHASE_12.md','utf8');

assert.match(server,/app\.get\('\/api\/games\/search'/);
assert.match(server,/page=Math\.max\(1,Number\(req\.query\.page\)\|\|1\)/);
assert.match(server,/year_from/);
assert.match(server,/year_to/);
assert.match(server,/sortMap=/);
assert.match(server,/app\.get\('\/api\/games\/filters'/);
assert.match(server,/app\.get\('\/api\/search'/);
assert.match(server,/app\.get\('\/api\/games\/:id\/access'/);
assert.match(server,/delivery_url/);
assert.match(server,/https:\/\/t\.me\/GameTrollAdmin/);
assert.match(server,/app\.post\('\/api\/admin\/images\/upload'/);
assert.match(server,/app\.get\('\/api\/admin\/images'/);
assert.match(server,/app\.delete\('\/api\/admin\/images\/:id'/);
assert.match(server,/verifyImageFile/);
assert.match(server,/image\/png/);
assert.match(server,/fileSize:5\*1024\*1024/);
assert.match(db,/idx_games_advanced/);
assert.match(db,/idx_images_created/);
assert.match(html,/class="filters"/);
assert.match(html,/id="gameConsole"/);
assert.match(html,/id="gamePlatform"/);
assert.match(html,/id="gameGenre"/);
assert.match(html,/id="gameSort"/);
assert.match(html,/id="gameYear"/);
assert.match(html,/async function loadGames\(/);
assert.match(html,/async function loadGames\(/);
assert.match(html,/id="gamesPager"/);
assert.match(unified,/gtAdminTab\('images'\)/);
assert.match(unified,/gtUploadImage/);
assert.match(unified,/gtDeleteImage/);
assert.match(unified,/gtPopulatePackSelector/);
assert.match(unified,/\/api\/games\/\'\+encodeURIComponent\(id\)\+\'\/access/);
assert.match(unified,/📦 دریافت پک/);
assert.match(phase,/مرحله ۱۲/);

const routes=[...server.matchAll(/app\.(get|post|patch|delete)\('([^']+)'/g)].map(m=>m[1]+' '+m[2]);
const counts=new Map();for(const r of routes)counts.set(r,(counts.get(r)||0)+1);
for(const [r,n] of counts)assert.equal(n,1,`duplicate route: ${r}`);

console.log('Phase 12 static tests: 35/35 passed');
