import assert from 'node:assert/strict';
import fs from 'node:fs';
const index=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const server=fs.readFileSync(new URL('../server.js',import.meta.url),'utf8');
const db=fs.readFileSync(new URL('../db.js',import.meta.url),'utf8');
assert.match(index,/id="ticketPage"/);
assert.match(index,/function ticketPath\(id,isAdmin\)/);
assert.match(index,/history\.pushState\(\{gtTicketBack:true/);
assert.match(index,/data-ticket-details/);
assert.match(index,/data-ticket-drawer/);
assert.match(index,/ticketBubbleRow \${side}/);
assert.match(index,/ticketBubbleRow \${side}/);
assert.match(index,/data-ticket-message/);
assert.match(index,/data-ticket-send/);
assert.match(index,/fetch\(API\+path,o\)/);
assert.match(index,/method:'POST',body:JSON\.stringify\(\{message\}\)/);
assert.match(index,/\/admin\/tickets\/.*\/messages/);
assert.match(index,/\/tickets\/.*\/messages/);
assert.match(server,/SELECT \* FROM tickets WHERE id=\? AND user_id=\?/);
assert.match(server,/requireAdmin/);
assert.match(server,/status==='closed'/);
assert.match(server,/status:'answered'/);
assert.match(server,/status:'investigating'/);
assert.match(server,/req\.body\?\.status==='closed'/);
assert.match(server,/tickets WHERE status!='closed'/);
assert.match(db,/DEFAULT 'investigating'/);
assert.match(db,/status IN \('new','open','pending','resolved'\)/);
console.log('Ticket chat, reply API, routing, security and status checks passed');
